### ISSUE TITLE
Why is there no gui?

### ISSUE THREAD

**Issue by alecss131** [gnustep/tools-windows-msvc#49] opened 2024-07-23 11:16 UTC
https://github.com/gnustep/libs-gui
https://github.com/gnustep/libs-back
https://github.com/gnustep/apps-gorm
How build this libraries (and is this possible?) for msvc?
This need gnustep-make package but this missed from this repo release

**Comment by gcasa** [comment] 2024-07-23 15:58
I am not sure I understand what you mean by "why is there no GUI".  Are you building the entire thing and there is no GUI presented?

**Comment by triplef** [comment] 2024-07-23 16:36
Is this a duplicate of #36?

**Comment by gcasa** [comment] 2024-07-23 16:51
> Is this a duplicate of #36?

I believe so.

**Closed** 2024-07-24 07:47 UTC
